### ISSUE TITLE
Adding VCH wizzard hangs on Network tab

### ISSUE THREAD

**Issue by mashbrno** [vmware/vic-ui#625]
vCenter Version: 6.7.0d
ESXi: VMware ESXi, 6.5.0, 6765664
VIC Plugin Version: v1.4.3.1367
Browser: Chome x64 69.0.3497.100, Windows 10,1809

Similar issue to already reported, but the versions of plugin and vCenter are higher and there is no error in Chrome Dev Tools, 
Last call to ui/tree/children?nodeTypeId=Datacenter&objRef=urn:vmomi:Datacenter:datacenter-21:1ba1c008-03d4-4e5b-8b6b-3ebf5687fcd6&treeId=vsphere.core.networkingInventorySpec is successfull and returns 9 networks.

**Comment by daydrim** [comment]
It seems that network tab works, but shows all the networks in the cluster as Not Configured and we can not choose the network.
vCenter: Version 6.7.0.20000
ESXi: 6.7.0, 10302608 
VIC Plugin: v1.4.4.1405
Chrome: 70.0.3538.102 (Official Build) (64-bit)

**Comment by mashbrno** [comment]
@daydrim Is there way to configure the network?

**Comment by zhoumeina** [comment]
@mashbrno , I know the vic-ui code from master has this issue, and it already has been fixed. I will test 1.4.4 to make sure everything works well.

**Comment by mashbrno** [comment]
Still persist with setup:
vCenter Version: 6.7.0U1
ESXi: VMware ESXi, 6.5.0, 6765664
VIC Plugin Version: v1.4.4.1405

**Comment by zhoumeina** [comment]
@mashbrno ， could you please provide a environment, because I can not reproduce this error in 1.4.4. Can you make a screenshot of network?  Did you add Dswitch in your vcenter? I think this could be a problem already resolved in vic 1.5

**Comment by mashbrno** [comment]
My problem might be unrelated with VIC - there are some ghost networks. See those attached to VMs, but not to hosts? I removed them from VMs, but this table doesn't seem to be refreshed.
![image](https://user-images.githubusercontent.com/7872442/48886276-aee44500-ee2b-11e8-8705-897546b6d437.png)

Another problem might be in `Failed to verify the vic-machine server at endpoint https://10.68.10.188:8443` but connecting via browser works fine (just notice about invalid SSL certificate).

No Dswitch exists in my deployment.

**Comment by zhoumeina** [comment]
@mashbrno , if no network exsit, it will hanging there in the network page. I am not sure what is your environment config. Did you add Dswitch under nested version? If so ,it can be the reason that vic 1.4 does not support nested dswitch. We have already fixed this in the current master branch.

**Comment by mashbrno** [comment]
I'm using single standard switch with topology on the screenshot (same at all 3 hosts). But as you can see the vCenter shows some networks, which are not bound to any host (eg. `Fortigate`, `EXTERNAL`). This might be the problem, but I have no idea how to remove them.

![image](https://user-images.githubusercontent.com/7872442/49424979-8ac62380-f79c-11e8-99d2-3f7916609580.png)

**Comment by zhoumeina** [comment]
@mashbrno , please confirm if you configed correct networks. If the network is correct. vic network tab will not hang up. We already fixed it in vic 1.5. To void this kind of issue. please use the latest vic version in vc.

**Comment by mashbrno** [comment]
Confirmed, dialog works now. Unfortunately my license doesn't allow me to use VIC, so I have to stick to Docker Swarm anyway. Pity.
